services:
  automl-wine-quality:
    build: .
    container_name: automl-wine-quality
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    command: python -m src.train
